# Generated by Django 3.1.1 on 2020-10-01 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the recipe', max_length=255, verbose_name='Recipe Title')),
                ('rcpCreatedOn', models.DateTimeField(auto_now_add=True, help_text='Date and Time when the recipe was created.', verbose_name='Recipe Created on')),
                ('type', models.CharField(choices=[('VEG', 'VEG'), ('NON-VEG', 'NON-VEG')], help_text='Is the recipe Veg or Non-Veg', max_length=255, verbose_name='VEG/NON-VEG')),
                ('cookingInstruction', models.CharField(help_text='Ingredients', max_length=3000, verbose_name='Ingredients')),
                ('ingredients', models.ManyToManyField(to='core.Ingredient')),
                ('tags', models.ManyToManyField(to='core.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
