# Generated by Django 3.1.1 on 2020-10-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cookingInstruction',
            field=models.CharField(blank=True, help_text='Ingredients', max_length=3000, verbose_name='Ingredients'),
        ),
    ]
